weights: yolov5m.pt
cfg: /home/ea/projects/yolov5/models/yolov5m.yaml
data: /home/ea/projects/yolov5/data/OCRSirius.yaml
hyp: /home/ea/projects/yolov5/data/hyp.OCRSirius.yaml
epochs: 100
batch_size: 16
img_size:
- 320
- 320
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs/train/exp26
total_batch_size: 16
